# Generated by Django 5.0.3 on 2024-03-15 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Caixa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valorInicial', models.FloatField()),
                ('valorAtual', models.FloatField()),
                ('dataHoraAberturaAtual', models.CharField(max_length=55)),
                ('isOpen', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=105)),
                ('cep', models.CharField(max_length=105)),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('numTelefone', models.CharField(max_length=11, unique=True)),
                ('status', models.BooleanField(default=False)),
                ('dataNascimento', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='DiaCaixa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataHoraAbertura', models.CharField(max_length=55)),
                ('dataHoraEncerramento', models.CharField(max_length=55)),
                ('valorInicial', models.FloatField()),
                ('valorFinal', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='EntradaMercadoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
                ('data', models.CharField(max_length=55)),
                ('valor', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='MetodoPagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo', models.CharField(max_length=55)),
                ('valor', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigoBarras', models.CharField(max_length=155)),
                ('nome', models.CharField(max_length=155)),
                ('tipo', models.CharField(max_length=55)),
                ('dataValidade', models.CharField(max_length=55)),
                ('qtdMinima', models.IntegerField()),
                ('quantidade', models.IntegerField()),
                ('valor', models.FloatField()),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(max_length=55)),
                ('total', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Bairro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=105)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bd_api_app.cidade')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('pessoa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bd_api_app.pessoa')),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('rg', models.CharField(max_length=9, unique=True)),
            ],
            bases=('bd_api_app.pessoa',),
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('pessoa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bd_api_app.pessoa')),
                ('cnpj', models.CharField(max_length=14, unique=True)),
            ],
            bases=('bd_api_app.pessoa',),
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('pessoa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bd_api_app.pessoa')),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('cargo', models.CharField(max_length=55)),
                ('salario', models.FloatField()),
                ('cargaHoraria', models.FloatField()),
            ],
            bases=('bd_api_app.pessoa',),
        ),
        migrations.CreateModel(
            name='Caixa_DiaCaixa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ownerCaixa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bd_api_app.caixa')),
                ('ownerDiaCaixa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bd_api_app.diacaixa')),
            ],
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rua', models.CharField(max_length=55)),
                ('numCasa', models.CharField(max_length=10)),
                ('complemento', models.CharField(max_length=55)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bd_api_app.bairro')),
            ],
        ),
        migrations.CreateModel(
            name='Conta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField()),
                ('dataVencimento', models.CharField(max_length=55)),
                ('tipoReceber', models.BooleanField()),
                ('ownerEntradaMercadoria', models.OneToOneField(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='bd_api_app.entradamercadoria')),
                ('ownerVenda', models.OneToOneField(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='bd_api_app.venda')),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=105)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bd_api_app.pessoa')),
            ],
        ),
        migrations.AddField(
            model_name='cidade',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bd_api_app.estado'),
        ),
        migrations.CreateModel(
            name='EntradaMercadoria_MetodoPagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ownerEntradaMercadoria', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bd_api_app.entradamercadoria')),
                ('ownerMetodoPagamento', models.ManyToManyField(to='bd_api_app.metodopagamento')),
            ],
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(max_length=55)),
                ('valor', models.FloatField()),
                ('ownerCaixa', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='bd_api_app.caixa')),
                ('ownerConta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bd_api_app.conta')),
            ],
        ),
        migrations.CreateModel(
            name='EntradaMercadoria_Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ownerEntradaMercadoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bd_api_app.entradamercadoria')),
                ('ownerProduto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bd_api_app.produto')),
            ],
        ),
        migrations.CreateModel(
            name='Venda_MetodoPagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ownerMetodoPagamento', models.ManyToManyField(to='bd_api_app.metodopagamento')),
                ('ownerVenda', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bd_api_app.venda')),
            ],
        ),
        migrations.CreateModel(
            name='VendaProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
                ('valor', models.FloatField()),
                ('ownerProduto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bd_api_app.produto')),
                ('ownerVenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bd_api_app.venda')),
            ],
        ),
        migrations.CreateModel(
            name='NotaFiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(max_length=55)),
                ('ownerVenda', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bd_api_app.venda')),
                ('listVendaProduto', models.ManyToManyField(to='bd_api_app.vendaproduto')),
            ],
        ),
        migrations.AddField(
            model_name='venda',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bd_api_app.cliente'),
        ),
        migrations.AddField(
            model_name='entradamercadoria',
            name='ownerFornecedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bd_api_app.fornecedor'),
        ),
    ]
