# Generated by Django 5.0.3 on 2024-03-16 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bd_api_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conta',
            name='ownerEntradaMercadoria',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bd_api_app.entradamercadoria'),
        ),
        migrations.AlterField(
            model_name='conta',
            name='ownerVenda',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bd_api_app.venda'),
        ),
    ]
