# Generated by Django 5.0.3 on 2024-03-16 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bd_api_app', '0002_alter_conta_ownerentradamercadoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagamento',
            name='ownerCaixa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bd_api_app.caixa'),
        ),
    ]
