# Generated by Django 5.0.1 on 2024-03-16 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bd_api_app', '0004_alter_caixa_diacaixa_ownerdiacaixa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
